"""empty message

Revision ID: 222c6a9a54b9
Revises: 8881ece9224f
Create Date: 2022-12-30 17:23:52.704990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222c6a9a54b9'
down_revision = '8881ece9224f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'description', 
                sa.String(), nullable=True
        ))
        batch_op.execute('UPDATE items SET description = "Hello world !"')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
